### PR TITLE
basic client side auth

### PR DESCRIPTION
**Pull request by ACPixel**
Added basic client side authentication. Feel free to check code. currently using one of my tokens, but you can get your own from https://mixer.com/lab . Also ?profile still works :) it will also keep you logged in across reloads and closes, until you click logout button. session is good for 1 year so no need to worry about that

### CODE REVIEW

**Review by Cheesiq — APPROVED** [review]
Thanks for the contribution, let's hope it doesn't break.

**Comment by ACPixel** [comment]
Did you replace it with your own oauth credentials from mixer with the mixlook domain as a url?

**Comment by CheesePwn** [comment]
> Did you replace it with your own oauth credentials from mixer with the mixlook domain as a url?
> […](#)
> On Dec 31 2019, at 10:17 pm, Cheese ***@***.***> wrote: Merged #3 ***@***.***/0?redirect=https%3A%2F%2Fgithub.com%2Forangopus%2Fmixlook%2Fpull%2F3&recipient=cmVwbHkrQUI2QzdOSEEyTjNZQ0xYTlZLT1pNRDU0REZXQTdFVkJOSEhCM1hKN1VZQHJlcGx5LmdpdGh1Yi5jb20%3D) into master. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Forangopus%2Fmixlook%2Fpull%2F3%3Femail_source%3Dnotifications%26email_token%3DAB6C7NEFCNX65OJ3VZ6SRVLQ3QYQ7A5CNFSM4I4MRB6KYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVXJY3TY%23event-2916322767&recipient=cmVwbHkrQUI2QzdOSEEyTjNZQ0xYTlZLT1pNRDU0REZXQTdFVkJOSEhCM1hKN1VZQHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB6C7NB3HJTMTVCYTXWXQCDQ3QYQ7ANCNFSM4I4MRB6A&recipient=cmVwbHkrQUI2QzdOSEEyTjNZQ0xYTlZLT1pNRDU0REZXQTdFVkJOSEhCM1hKN1VZQHJlcGx5LmdpdGh1Yi5jb20%3D).

Oops didn't even think of that. Thanks

**Comment by ACPixel** [comment]
LOL

**Pull request merged**
